=pod

=head1 QUICK OBJECTS

=over 4

=item Quick objects were concieved as an api stand-in

=item Emulates objects that provide fairly static information

=item Useful when the information in the object is not relivant to the test

=back

An example function to test:

    sub add_and_append {
        my ( $numA, $numB, $subsystem ) = @_;
        my $sum = $numA + $numB;

        return $subsystem->system_name . ":" . $sum;
    }

=over 4

=item We only want to test the addition, and the appending

=item We do not really care what subsystem->system_name returns (tested elsware)

=item Subsystem->new() needs 20 arguments, all are used to by system_name()

=back

Thats where quick objects come in:

    is(
        add_and_append( 2, 3, qobj( system_name => 'foo' )),
        "foo:5",
        "add_and_append works"
    );

=over 4

=item Next: L<https://github.com/exodist/Mock-Quick/blob/master/lib/Mock/Quick/Presentation/slideC.pod>

=item Previous: L<https://github.com/exodist/Mock-Quick/blob/master/lib/Mock/Quick/Presentation/slideA.pod>

=back

=cut
