=pod

=head1 MOCKING CLASSES

Sometimes a quick object is not sufficient.

=over 4

=item The object you need to mock is instantiated inside the function you're testing

=item You want to preserve the original class, but you need to override a subset of methods

=item You want to replace the original class and prevent it from loading

=item You want to implement a temporary but re-usable class specification

=back

Next: L<https://github.com/exodist/Mock-Quick/blob/master/lib/Mock/Quick/Presentation/slideI.pod>
Previous: L<https://github.com/exodist/Mock-Quick/blob/master/lib/Mock/Quick/Presentation/slideG.pod>

=cut
